### PR TITLE
Added route , controller and service logic for searching courses based

### PR DESCRIPTION
**Pull request by tejaswini22199**
on title and instructors.

solves issue #31

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
please accommodate the changes to allow 
- listing all courses
- listing on based on the count of students
- listing on basis of title / body
- listing by category

**Comment by tejaswini22199** [comment]
do you want separate APIs for each or single API?

**Comment by tejaswini22199** [comment]
> please accommodate the changes to allow
> 
> * listing all courses
> * listing on based on the count of students
> * listing on basis of title / body
> * listing by category

do you want separate APIs for each or single API? @YashKumarVerma

**Comment by YashKumarVerma** [comment]
if a single Api can do this, best.

**Comment by tejaswini22199** [comment]
closing this pr since I created a separate branch and created another pr for the same. sorry for the confusion.
check #54

**Pull request closed without merging**
